name: Bundle deno and commit files
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno test -A tests/mod.ts

  bundle:
    needs: ["test"]
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install

      - run: deno bundle mod.ts > dist/browser.bundle.js
      - run: echo "import fetch from 'node-fech'" > dist/index.mjs
      - run: cat dist/browser.bundle.js >> dist/index.mjs
      - run: yarn esbuild dist/browser.bundle.js --outfile=dist/index.js --platform=node --sourcemap=inline --target=es2020 --format=cjs
      - run: sed -i '1s/^/const fetch = require("node-fetch");/' dist/index.js
      - run: yarn format
      - run: deno run -A --no-check --unstable bundlewithtypes.ts
      - run: git add .
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'SkyBlockDev' 
          git config --global user.email '72335827+SkyBlockDev@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Update files"
          git push
