name: Bundle deno and commit files
on: [push]
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: denoland/setup-deno@v1
      - uses: actions/setup-node@v2
        with:
        node-version: '14'
        cache: 'yarn'
      - run: yarn install
      - run: yarn test
        with:
        deno-version: vx.x.x
      - run: deno bundle mod.ts >> dist/browser.bundle.js
      - run: yarn esbuild dist/browser.bundle.js --outfile=node.js --platform=node --sourcemap=inline --target=es2020 --format=cjs

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'SkyBlockDev' 
          git config --global user.email '72335827+SkyBlockDev@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated changes"
          git push
